[package]
name = "clooe"
version = "0.1.0"
edition = "2021"
authors = ["994386508@qq.com"]
license = "MIT"
homepage = ""
repository = ""
documentation = ""
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
